### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by drnic** [logsearch/logsearch-for-websites#3]
```
./bin/test
rm -rf target
mkdir target
===> Building ...
mkdir -p target/kibana-dashboards
vendor/addon-common/bin/build.sh src/parsers/logsearch-for-weblogs.filters.conf.erb > target/logsearch-for-weblogs.filters.conf
vendor/addon-common/bin/build.sh src/kibana-dashboards/Geo-IP.json > target/kibana-dashboards/Geo-IP.json
===> Artifacts:
target
├── kibana-dashboards
│   └── Geo-IP.json
└── logsearch-for-weblogs.filters.conf

1 directory, 2 files
===> Testing ...
vendor/addon-common/bin/test.sh
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :elasticsearch=>true, :broken=>true}
Invalid setting for geoip filter plugin:

  filter {
    geoip {
      # This setting must be a path
      # File does not exist or cannot be opened /var/vcap/packages/logstash/logstash/vendor/geoip/GeoLiteCity.dat
      database => "/var/vcap/packages/logstash/logstash/vendor/geoip/GeoLiteCity.dat"
      ...
    }
  } {:level=>:error}
FInvalid setting for geoip filter plugin:

  filter {
    geoip {
      # This setting must be a path
      # File does not exist or cannot be opened /var/vcap/packages/logstash/logstash/vendor/geoip/GeoLiteCity.dat
      database => "/var/vcap/packages/logstash/logstash/vendor/geoip/GeoLiteCity.dat"
      ...
    }
  } {:level=>:error}
F

Failures:

  1) All logsearch-for-weblogs parsers nginx_combined log over syslog "{"@type":"syslog","@message":"<14>1 2015-01-16T15:1..." when processed
     Failure/Error: let(:pipeline) { LogStash::Pipeline.new(config) }
     LogStash::ConfigurationError:
       Something is wrong with your configuration.
     # ./vendor/logstash/lib/logstash/config/mixin.rb:96:in `config_init'
     # ./vendor/logstash/lib/logstash/filters/base.rb:129:in `initialize'
     # ./vendor/logstash/lib/logstash/pipeline.rb:258:in `plugin'
     # (eval):43:in `initialize'
     # ./vendor/logstash/lib/logstash/pipeline.rb:28:in `initialize'
     # ./vendor/logstash/spec/test_utils.rb:65:in `pipeline'
     # ./vendor/logstash/spec/test_utils.rb:77:in `results'
     # ./vendor/logstash/spec/test_utils.rb:92:in `subject'
     # ./test/parsers/logsearch-for-weblogs.spec.rb:18:in `(root)'
     # ./test/parsers/logsearch-for-weblogs.spec.rb:18:in `(root)'
     # ./vendor/logstash/lib/logstash/runner.rb:154:in `run'

  2) nginx_combined geoip "{"@type":"nginx_combined","@message":"216.58.208.46..." when processed
     Failure/Error: let(:pipeline) { LogStash::Pipeline.new(config) }
     LogStash::ConfigurationError:
       Something is wrong with your configuration.
     # ./vendor/logstash/lib/logstash/config/mixin.rb:96:in `config_init'
     # ./vendor/logstash/lib/logstash/filters/base.rb:129:in `initialize'
     # ./vendor/logstash/lib/logstash/pipeline.rb:258:in `plugin'
     # (eval):13:in `initialize'
     # ./vendor/logstash/lib/logstash/pipeline.rb:28:in `initialize'
     # ./vendor/logstash/spec/test_utils.rb:65:in `pipeline'
     # ./vendor/logstash/spec/test_utils.rb:77:in `results'
     # ./vendor/logstash/spec/test_utils.rb:92:in `subject'
     # ./test/parsers/nginx_combined.spec.rb:19:in `(root)'
     # ./test/parsers/nginx_combined.spec.rb:19:in `(root)'
     # ./vendor/logstash/lib/logstash/runner.rb:154:in `run'

Finished in 1.82 seconds
2 examples, 2 failures

Failed examples:

rspec ./vendor/logstash/spec/test_utils.rb:94 # All logsearch-for-weblogs parsers nginx_combined log over syslog "{"@type":"syslog","@message":"<14>1 2015-01-16T15:1..." when processed
rspec ./vendor/logstash/spec/test_utils.rb:94 # nginx_combined geoip "{"@type":"nginx_combined","@message":"216.58.208.46..." when processed
rake aborted!
Command failed with status (1): [vendor/addon-common/bin/test.sh...]
/Users/drnic/Projects/logsearch/logsearch-for-websites/Rakefile:19:in `block in <top (required)>'
/Users/drnic/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/drnic/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by drnic** [comment]
I can see this has something to do with needing `/var/vcap/packages/...` setup on my laptop/workspace machine.

**Comment by mrdavidlaing** [comment]
@drnic, Logstash 1.4 has a bug which forces you to hardcode the path to the `GeoLiteCity.dat` file

`/var/vcap/packages/logstash/logstash/vendor/geoip/GeoLiteCity.dat` is the location of that file in a "production" logsearch deployment.

If you run the tests inside the https://github.com/logsearch/workspace VM we have a workaround for this issue (basically a symlink causing `/var/vcap/packages/logstash/logstash/vendor/geoip/GeoLiteCity.dat` to exist).

I see 3 ways forward:
1.  Run inside the https://github.com/logsearch/workspace VM (the "supported" way)
2.  Make `/var/vcap/packages/logstash/logstash/vendor/geoip/GeoLiteCity.dat` exist in your environment
3.  Wait for us to upgrade to logstash 1.5.0, which doesn't have this bug (work planned to happen towards the end of March)

**Comment by drnic** [comment]
I'm ok with waiting; if each plugin can consistently have a bin/build.sh
(in addition to a bin/build-and-test.sh) so that we can just automate the
build sequence for each plugin and avoid the temporarily failing tests?
